packages:
  - "packages/*"
  - "packages/create-react-server/test"
  - "examples/*"
  - "docs"
  - "test"
allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  playwright-chromium: true
  protobufjs: true
  simple-git-hooks: true
gitChecks: false
minimumReleaseAgeExclude:
  - '@rolldown/binding-android-arm64@1.1.1'
  - '@rolldown/binding-darwin-arm64@1.1.1'
  - '@rolldown/binding-darwin-x64@1.1.1'
  - '@rolldown/binding-freebsd-x64@1.1.1'
  - '@rolldown/binding-linux-arm-gnueabihf@1.1.1'
  - '@rolldown/binding-linux-arm64-gnu@1.1.1'
  - '@rolldown/binding-linux-arm64-musl@1.1.1'
  - '@rolldown/binding-linux-ppc64-gnu@1.1.1'
  - '@rolldown/binding-linux-s390x-gnu@1.1.1'
  - '@rolldown/binding-linux-x64-gnu@1.1.1'
  - '@rolldown/binding-linux-x64-musl@1.1.1'
  - '@rolldown/binding-openharmony-arm64@1.1.1'
  - '@rolldown/binding-wasm32-wasi@1.1.1'
  - '@rolldown/binding-win32-arm64-msvc@1.1.1'
  - '@rolldown/binding-win32-x64-msvc@1.1.1'
  - rolldown@1.1.1
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@vercel/speed-insights"
  - better-sqlite3
  - esbuild
  - playwright-chromium
  - simple-git-hooks
overrides:
  "object-path": "0.11.8"
  "ws": "8.20.1"
peerDependencyRules:
  allowedVersions:
    "react": ">=19.0.0 <20.0.0"
    "react-dom": ">=19.0.0 <20.0.0"
    "vite": ">=8.0.0 <9.0.0"
