packages:
  - "packages/*"
  - "examples/*"
  - "docs"
  - "test"
gitChecks: false
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@swc/core"
  - "@vercel/speed-insights"
  - better-sqlite3
  - esbuild
  - playwright-chromium
  - simple-git-hooks
