# This issue template is based on https://github.com/vitejs/vite/tree/main/.github/ISSUE_TEMPLATE
blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/lazarv/react-server/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
