import { existsSync, readFileSync } from "node:fs";
import { cp } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import * as sys from "@lazarv/react-server/lib/sys.mjs";
import {
  banner,
  createAdapter,
  message,
  success,
  writeJSON,
} from "@lazarv/react-server/adapters/core";
import { writeFile } from "node:fs/promises";

const cwd = sys.cwd();
const dockerDir = join(cwd, ".docker");
const outDir = dockerDir;
const outStaticDir = join(outDir, "static");
const outServerDir = join(outDir, "server");
const adapterDir = dirname(fileURLToPath(import.meta.url));

export const adapter = createAdapter({
  name: "Docker",
  outDir,
  outStaticDir,
  outServerDir,
  handler: async function ({ adapterOptions, copy, options }) {
    banner("copying server entry", { emoji: "🐳" });
    const entryFile = join(outServerDir, "index.mjs");
    await cp(join(adapterDir, "server/index.mjs"), entryFile);
    success("server entry created");

    await copy.dependencies(outServerDir, [entryFile]);

    banner("generating Docker configuration", { emoji: "⚙️" });

    // Try to get app name from adapter options or package.json
    let appName = adapterOptions?.name;
    if (!appName) {
      const packageJsonPath = join(cwd, "package.json");
      if (existsSync(packageJsonPath)) {
        try {
          const packageJson = JSON.parse(
            readFileSync(packageJsonPath, "utf-8")
          );
          appName = packageJson.name?.replace(/^@[^/]+\//, "");
        } catch {
          // Ignore parsing errors
        }
      }
    }
    appName = appName || "react-server-app";

    const port = adapterOptions?.port ?? 3000;
    const nodeVersion = adapterOptions?.nodeVersion ?? "20-alpine";

    message("creating", "package.json");
    await writeJSON(join(outDir, "package.json"), {
      name: appName,
      type: "module",
      private: true,
      scripts: {
        start: `cd server && node index.mjs`,
      },
    });

    message("creating", "Dockerfile");
    const dockerfile = generateDockerfile({
      nodeVersion,
      port,
      sourcemap: options.sourcemap,
    });
    await writeFile(join(outDir, "Dockerfile"), dockerfile);

    message("creating", ".dockerignore");
    await writeFile(
      join(outDir, ".dockerignore"),
      [
        "node_modules",
        "npm-debug.log",
        "Dockerfile",
        ".dockerignore",
        ".git",
        ".gitignore",
        "",
      ].join("\n")
    );

    success("Docker configuration created");

    return { appName };
  },
  deploy: ({ adapterOptions, handlerResult }) => {
    const tag =
      adapterOptions?.tag ??
      `${handlerResult.appName ?? "react-server-app"}:latest`;
    return {
      command: "docker",
      args: ["build", "-t", tag, ".docker"],
      message: `\nRun the image with:\n  docker run -p ${adapterOptions?.port ?? 3000}:${adapterOptions?.port ?? 3000} ${tag}`,
    };
  },
});

export default function defineConfig(adapterOptions) {
  return async (_, root, options) => adapter(adapterOptions, root, options);
}

function generateDockerfile({ nodeVersion, port, sourcemap }) {
  const nodeOptions = sourcemap
    ? 'ENV NODE_OPTIONS="--enable-source-maps"'
    : "";

  return `# Auto-generated by @lazarv/react-server Docker adapter
FROM node:${nodeVersion}

ARG PORT=${port}
ENV PORT=$PORT
ENV NODE_ENV=production
${nodeOptions ? `${nodeOptions}\n` : ""}
WORKDIR /app

# Copy pre-built application
COPY package.json ./
COPY server/ ./server/
COPY static/ ./static/

# Install tini for proper signal handling and create non-root user
RUN apk add --no-cache tini && \\
  addgroup -g 1001 -S nodejs && \\
  adduser -S nodejs -u 1001 && \\
  chown -R nodejs:nodejs /app
USER nodejs

EXPOSE $PORT

# Set cwd to server/ so node-loader resolves .react-server/ build output correctly
WORKDIR /app/server

# Use tini as init process for proper signal handling
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "index.mjs"]
`;
}
