import { join } from "node:path";

import {
  hostname,
  page,
  server,
  waitForChange,
  waitForHydration,
} from "playground/utils";
import { beforeAll } from "vitest";
import { describe, expect, test } from "vitest";

process.chdir(join(process.cwd(), "../examples/typed-file-router"));

beforeAll(async () => {
  await server(null);
});

// ── Basic route rendering ──

describe("typed-file-router — basic routes", () => {
  test("renders home page at /", async () => {
    await page.goto(hostname);
    await page.waitForLoadState("load");
    expect(await page.textContent("body")).toContain(
      "Welcome to Typed File Router"
    );
  });

  test("renders about page at /about", async () => {
    await page.goto(`${hostname}/about`);
    await page.waitForLoadState("load");
    expect(await page.textContent("body")).toContain("About");
    expect(await page.textContent("body")).toContain(
      "simple page with no dynamic params"
    );
  });

  test("renders root layout with navigation", async () => {
    await page.goto(hostname);
    await page.waitForLoadState("load");
    // The root layout should have a nav with typed links
    const nav = await page.$("nav");
    expect(nav).not.toBeNull();
    // Nav should have links generated by typed route descriptors
    const navText = await nav.textContent();
    expect(navText).toContain("Home");
    expect(navText).toContain("About");
    expect(navText).toContain("User 42");
    expect(navText).toContain("Dashboard");
  });
});

// ── Dynamic user route with Zod validation ──

describe("typed-file-router — user route ([id])", () => {
  test("renders user page with valid numeric id", async () => {
    await page.goto(`${hostname}/user/42`);
    await page.waitForLoadState("load");
    expect(await page.textContent("body")).toContain("User Profile");
    expect(await page.textContent("body")).toContain("42");
  });

  test("renders user page with different id", async () => {
    await page.goto(`${hostname}/user/99`);
    await page.waitForLoadState("load");
    expect(await page.textContent("body")).toContain("User Profile");
    expect(await page.textContent("body")).toContain("99");
  });

  test("user page has typed Link to User 99", async () => {
    await page.goto(`${hostname}/user/42`);
    await page.waitForLoadState("load");
    // [id].page.tsx has user.Link params={{ id: "99" }}
    const link99 = await page.$('a[href="/user/99"]');
    expect(link99).not.toBeNull();
    expect(await link99.textContent()).toContain("User 99");
  });
});

// ── Client components ──

describe("typed-file-router — client components", () => {
  test("renders clock client component at /clock", async () => {
    await page.goto(`${hostname}/clock`);
    await page.waitForLoadState("load");
    await waitForHydration();
    expect(await page.textContent("body")).toContain("Clock (Client Page)");
    expect(await page.textContent("body")).toContain("live clock");
  });

  test("renders interactive counter at /counter", async () => {
    await page.goto(`${hostname}/counter`);
    await page.waitForLoadState("load");
    await waitForHydration();
    expect(await page.textContent("body")).toContain("Counter (Client Page)");
    expect(await page.textContent("body")).toContain("Count:");

    // Counter should be interactive — click and verify increment
    const button = await page.$("button");
    expect(button).not.toBeNull();
    expect(await button.textContent()).toContain("Count: 0");
    await button.click();
    expect(await button.textContent()).toContain("Count: 1");
    await button.click();
    expect(await button.textContent()).toContain("Count: 2");
  });
});

// ── Dashboard with parallel routes/outlets ──

describe("typed-file-router — dashboard layout and outlets", () => {
  test("renders dashboard page at /dashboard", async () => {
    await page.goto(`${hostname}/dashboard`);
    await page.waitForLoadState("load");
    expect(await page.textContent("body")).toContain(
      "Welcome to the dashboard"
    );
    expect(await page.textContent("body")).toContain("typed outlets");
  });

  test("renders dashboard layout structure with sidebar and content", async () => {
    await page.goto(`${hostname}/dashboard`);
    await page.waitForLoadState("load");
    // Layout should have both sidebar and content sections
    expect(await page.textContent("body")).toContain("Sidebar");
    expect(await page.textContent("body")).toContain("Content");
  });
});

// ── Virtual routes ──

describe("typed-file-router — virtual routes", () => {
  test("renders virtual route at /virtual", async () => {
    await page.goto(`${hostname}/virtual`);
    await page.waitForLoadState("load");
    expect(await page.textContent("body")).toContain("Virtual Route Page");
    expect(await page.textContent("body")).toContain(
      "virtual route in the config"
    );
  });
});

// ── Client-side navigation via typed Links ──

describe("typed-file-router — client-side navigation", () => {
  test("navigates to about via typed Link click", async () => {
    await page.goto(hostname);
    await page.waitForLoadState("load");
    await waitForHydration();

    const prevUrl = page.url();
    const aboutLink = await page.$('nav a[href="/about"]');
    expect(aboutLink).not.toBeNull();
    await aboutLink.click();
    await waitForChange(null, () => page.url(), prevUrl);

    expect(page.url()).toContain("/about");
    expect(await page.textContent("body")).toContain("About");
  });

  test("navigates to dynamic user route via typed Link", async () => {
    await page.goto(hostname);
    await page.waitForLoadState("load");
    await waitForHydration();

    const prevUrl = page.url();
    const userLink = await page.$('nav a[href="/user/42"]');
    expect(userLink).not.toBeNull();
    await userLink.click();
    await waitForChange(null, () => page.url(), prevUrl);

    expect(page.url()).toContain("/user/42");
    expect(await page.textContent("body")).toContain("User Profile");
    expect(await page.textContent("body")).toContain("42");
  });

  test("navigates from user page to User 99 via typed Link", async () => {
    await page.goto(`${hostname}/user/42`);
    await page.waitForLoadState("load");
    await waitForHydration();

    const prevUrl = page.url();
    const user99Link = await page.$('a[href="/user/99"]');
    expect(user99Link).not.toBeNull();
    await user99Link.click();
    await waitForChange(null, () => page.url(), prevUrl);

    expect(page.url()).toContain("/user/99");
    expect(await page.textContent("body")).toContain("99");
  });
});

// ── Resource routes ──

describe("typed-file-router — resource routes", () => {
  test("renders todos page with server-loaded data at /todos", async () => {
    await page.goto(`${hostname}/todos`);
    await page.waitForLoadState("load");
    await waitForHydration();
    expect(await page.textContent("body")).toContain("Todos");
    // Verify todo items from the server resource loader
    expect(await page.textContent("body")).toContain("Set up file router");
    expect(await page.textContent("body")).toContain("Add resource files");
    expect(await page.textContent("body")).toContain("Deploy to production");
  });

  test("todos page shows todo list with correct item count", async () => {
    await page.goto(`${hostname}/todos`);
    await page.waitForLoadState("load");
    await waitForHydration();
    const listItems = await page.$$('[data-testid="todos-list"] li');
    expect(listItems.length).toBe(7);
  });

  test("navigates to todos via typed Link click", async () => {
    await page.goto(hostname);
    await page.waitForLoadState("load");
    await waitForHydration();

    const prevUrl = page.url();
    const todosLink = await page.$('nav a[href="/todos"]');
    expect(todosLink).not.toBeNull();
    await todosLink.click();
    await waitForChange(null, () => page.url(), prevUrl);

    expect(page.url()).toContain("/todos");
    expect(await page.textContent("body")).toContain("Todos");
  });

  test("todos page has filter links", async () => {
    await page.goto(`${hostname}/todos`);
    await page.waitForLoadState("load");
    await waitForHydration();
    expect(await page.textContent("body")).toContain("all");
    expect(await page.textContent("body")).toContain("active");
    expect(await page.textContent("body")).toContain("completed");
  });
});

// ── Browser history ──

describe("typed-file-router — browser history", () => {
  test("back and forward navigation works", async () => {
    await page.goto(hostname);
    await page.waitForLoadState("load");
    await waitForHydration();

    // Navigate to about
    await page.goto(`${hostname}/about`);
    await page.waitForLoadState("load");

    // Navigate to dashboard
    await page.goto(`${hostname}/dashboard`);
    await page.waitForLoadState("load");

    // Go back
    await page.goBack();
    await page.waitForLoadState("load");
    expect(page.url()).toContain("/about");

    // Go back again
    await page.goBack();
    await page.waitForLoadState("load");
    expect(page.url()).toBe(`${hostname}/`);

    // Go forward
    await page.goForward();
    await page.waitForLoadState("load");
    expect(page.url()).toContain("/about");
  });
});
