# This workflow is based on https://github.com/vitejs/vite/tree/main/.github/workflows
name: Lock Closed Issues 🔒

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  action:
    name: Lock closed issues 🔒
    if: github.repository == 'lazarv/react-server'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: "30"
          issue-comment: |
            This issue has been locked since it has been closed for more than 30 days.

            If you have found a concrete bug or regression related to it, please open a new [bug report](https://github.com/lazarv/react-server/issues/new/choose) with a reproduction against the latest version of @lazarv/react-server. If you have any other comments you should create a new [discussion](https://github.com/lazarv/react-server/discussions).
          issue-lock-reason: ""
          process-only: "issues"
